/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        background: "#fff8f6",
        surface: "#fff8f6",
        "surface-bright": "#fff8f6",
        "surface-dim": "#e3d7d5",
        "surface-tint": "#86513d",
        "surface-variant": "#ece0dd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fdf1ee",
        "surface-container": "#f8ebe9",
        "surface-container-high": "#f2e6e3",
        "surface-container-highest": "#ece0dd",
        "inverse-surface": "#352f2d",
        "inverse-on-surface": "#faeeeb",
        "inverse-primary": "#fbb69e",

        primary: "#834f3b",
        "on-primary": "#ffffff",
        "primary-container": "#9f6752",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#fbb69e",
        "on-primary-fixed": "#341003",
        "on-primary-fixed-variant": "#6a3a28",

        secondary: "#75584e",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed7cb",
        "on-secondary-container": "#795c52",
        "secondary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#e4beb3",
        "on-secondary-fixed": "#2b160f",
        "on-secondary-fixed-variant": "#5b4138",

        tertiary: "#2b6561",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#457e7a",
        "on-tertiary-container": "#f3fffd",
        "tertiary-fixed": "#b3eee8",
        "tertiary-fixed-dim": "#97d1cc",
        "on-tertiary-fixed": "#00201e",
        "on-tertiary-fixed-variant": "#0e4f4c",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        "on-background": "#201a19",
        "on-surface": "#201a19",
        "on-surface-variant": "#52443f",
        outline: "#84736e",
        "outline-variant": "#d7c2bc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        gutter: "20px",
        md: "24px",
        margin: "32px",
        lg: "40px",
        xl: "64px",
      },
      fontFamily: {
        display: ['"Newsreader"', "serif"],
        serif: ['"Newsreader"', "serif"],
        sans: ['"Work Sans"', "system-ui", "sans-serif"],
      },
      fontSize: {
        display: [
          "80px",
          { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "600" },
        ],
        h1: ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        h2: ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
